// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Kawsay Developer Agent",
            "url": "http://www.example.com",
            "email": "dev.agent@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/academicSessions": {
            "get": {
                "description": "Retrieves a collection of all academic sessions of any type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get all academic sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.AcademicSession"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/academicSessions/{id}": {
            "get": {
                "description": "Retrieves a single academic session by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get a specific academic session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the academic session",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.AcademicSession"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/classes": {
            "get": {
                "description": "Retrieves a collection of all scheduled classes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classes"
                ],
                "summary": "Get all classes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Class"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/classes/{id}": {
            "get": {
                "description": "Retrieves a single class by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classes"
                ],
                "summary": "Get a specific class",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the class",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.Class"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/classes/{id}/categories": {
            "get": {
                "description": "Retrieves a collection of grading categories for a given class.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classes"
                ],
                "summary": "Get categories for a class",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the class",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Category"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/courses": {
            "get": {
                "description": "Retrieves a collection of all courses from the catalog.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get all courses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Course"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "description": "Retrieves a single course by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get a specific course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the course",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.Course"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/enrollments": {
            "get": {
                "description": "Retrieves a collection of all user enrollments in classes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollments"
                ],
                "summary": "Get all enrollments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Enrollment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/enrollments/{id}": {
            "get": {
                "description": "Retrieves a single enrollment by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Enrollments"
                ],
                "summary": "Get a specific enrollment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the enrollment",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.Enrollment"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gradingPeriods": {
            "get": {
                "description": "Retrieves a collection of all academic sessions with type 'gradingPeriod'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get all grading periods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.AcademicSession"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/gradingPeriods/{id}": {
            "get": {
                "description": "Retrieves a single grading period by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get a specific grading period",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the grading period",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.AcademicSession"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orgs": {
            "get": {
                "description": "Retrieves a collection of all organizations, including schools and districts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orgs"
                ],
                "summary": "Get all organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Org"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/orgs/{id}": {
            "get": {
                "description": "Retrieves a single organization by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orgs"
                ],
                "summary": "Get a specific organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the organization",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.Org"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/schools": {
            "get": {
                "description": "Retrieves a collection of all organizations with type 'school'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schools"
                ],
                "summary": "Get all schools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.Org"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/schools/{id}": {
            "get": {
                "description": "Retrieves a single school by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schools"
                ],
                "summary": "Get a specific school",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the school",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.Org"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/students": {
            "get": {
                "description": "Retrieves a collection of all users with the role 'student'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Get all students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/students/{id}": {
            "get": {
                "description": "Retrieves a single student by their sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Get a specific student",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the student",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/teachers": {
            "get": {
                "description": "Retrieves a collection of all users with the role 'teacher'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teachers"
                ],
                "summary": "Get all teachers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/teachers/{id}": {
            "get": {
                "description": "Retrieves a single teacher by their sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teachers"
                ],
                "summary": "Get a specific teacher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the teacher",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/terms": {
            "get": {
                "description": "Retrieves a collection of all academic sessions with type 'term'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get all terms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.AcademicSession"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/terms/{id}": {
            "get": {
                "description": "Retrieves a single term by its sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Academic Sessions"
                ],
                "summary": "Get a specific term",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the term",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.AcademicSession"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Retrieves a collection of all users, including students and teachers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/main.User"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Retrieves a single user by their sourcedId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get a specific user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SourcedId of the user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/main.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AcademicSession": {
            "description": "Represents a time period in the academic calendar, such as a term, semester, or grading period.",
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "dateLastModified": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "metadata": {},
                "parent": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "schoolYear": {
                    "type": "string"
                },
                "sourcedId": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "'gradingPeriod', 'semester', 'schoolYear', 'term'",
                    "type": "string"
                }
            }
        },
        "main.Category": {
            "description": "Represents a grading category within a class.",
            "type": "object",
            "properties": {
                "dateLastModified": {
                    "type": "string"
                },
                "metadata": {},
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "main.Class": {
            "description": "Represents a specific instance of a course for a particular term and school.",
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "classType": {
                    "description": "'homeroom', 'scheduled'",
                    "type": "string"
                },
                "course": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "dateLastModified": {
                    "type": "string"
                },
                "grades": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "metadata": {},
                "periods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "school": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subjectCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "terms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "main.Course": {
            "description": "Represents a course in the course catalog.",
            "type": "object",
            "properties": {
                "courseCode": {
                    "type": "string"
                },
                "dateLastModified": {
                    "type": "string"
                },
                "grades": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metadata": {},
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "schoolYear": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subjectCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "main.Enrollment": {
            "description": "Represents the link between a user and a class for a specific role.",
            "type": "object",
            "properties": {
                "beginDate": {
                    "type": "string"
                },
                "class": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "dateLastModified": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "metadata": {},
                "primary": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "school": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/main.GUIDRef"
                }
            }
        },
        "main.GUIDRef": {
            "description": "A reference to another OneRoster object.",
            "type": "object",
            "properties": {
                "href": {
                    "type": "string"
                },
                "sourcedId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.Org": {
            "description": "Represents an organization, such as a school or district.",
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "dateLastModified": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "metadata": {},
                "name": {
                    "type": "string"
                },
                "parent": {
                    "$ref": "#/definitions/main.GUIDRef"
                },
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "description": "e.g., 'school', 'district'",
                    "type": "string"
                }
            }
        },
        "main.User": {
            "description": "Represents a person within the system, such as a student or a teacher.",
            "type": "object",
            "properties": {
                "dateLastModified": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "enabledUser": {
                    "type": "boolean"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "metadata": {},
                "orgs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.GUIDRef"
                    }
                },
                "role": {
                    "description": "'student', 'teacher'",
                    "type": "string"
                },
                "sourcedId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "userIds": {
                    "type": "array",
                    "items": {}
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/ims/oneroster/v1p1",
	Schemes:          []string{},
	Title:            "OneRoster Mock API",
	Description:      "This is a mock server for the OneRoster v1p1 API specification.\nIt serves a large, procedurally generated, in-memory dataset for testing purposes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
